embedding_size: 64
reg_weight: 0.1

# lambda_0: [0.02, 0.01]
# alpha: [0.02, 0.03]

# lambda_0: [0.01]
# alpha: [0.01]

lambda_0: [2e-2, 1e-3, 5e-3, 1e-2]
alpha: [2e-2, 1e-3, 5e-3, 1e-2]
beta: [2e-2, 1e-3, 5e-3, 1e-2]

# to prevent increasing model capcity than villina base model, we restrict the inner sizes equaling to the embedding size
prompt_size: 64
share_size: 64

hyper_parameters: ["lambda_0", "alpha", "beta"]