embedding_size: 64
weight_size: [64]
reg_weight: 1e-01

lambda_0: [0.01, 0.05, 0.1]
alpha: [0.01, 0.05, 0.1]
beta: [0.01, 0.05, 0.1]

# to prevent increasing model capcity than villina base model, we restrict the inner sizes equaling to the embedding size
prompt_size: 64
share_size: 64

hyper_parameters: ["lambda_0", "alpha", "beta"]