# Common Features
USER_ID_FIELD: userID
ITEM_ID_FIELD: itemID
#RATING_FIELD: rating
TIME_FIELD: timestamp

filter_out_cod_start_users: True

inter_file_name: 'ml1m.inter'

field_separator: "\t"

# sensitive attributes
feature_columns: ["u_gender"]